### ISSUE TITLE
Bug: string highlighting in jsonInput is not visible in light mode

### ISSUE THREAD

**Issue by marichka-offen** [PrefectHQ/orion-design#1120] opened 2023-02-06 19:54 UTC
<img width="732" alt="Screenshot 2023-02-06 at 2 51 44 PM" src="https://user-images.githubusercontent.com/40467112/217071245-59a615bf-a402-4cef-bc88-a0e8640b22c2.png">
<img width="717" alt="Screenshot 2023-02-06 at 2 51 32 PM" src="https://user-images.githubusercontent.com/40467112/217071247-224b0efa-d36d-4da5-b1b0-fc66a2397805.png">

**Comment by zhen0** [comment] 2023-02-06 20:19
@znicholasbrown - will this be fixed in your code input updates at all?

**Comment by zhen0** [comment] 2023-02-06 20:22
duplicate of https://github.com/PrefectHQ/prefect/issues/8348

**Closed by zhen0** 2023-02-06 20:22 UTC
Labels: priority:high

**Comment by znicholasbrown** [comment] 2023-02-06 20:36
Indeed! Only we'll need to swap out the components before this fix will go live
